<a href="https://colab.research.google.com/github/juliavassimon/python_aula/blob/main/PySparks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#numpy trabalha com array (matrizes)
#precisa instalar a biblioteca
#dados homogeneos (dados SQL)
import numpy as np
data = [1,2,3,4,5,6] #isso é uma lista
array = np.array(data)
print(type(array))
print(array)


<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [4]:
import numpy as np
data = [[1,2,3],[4,5,6]] #isso é um vetor dimensional (matriz)
array = np.array(data)
print(type(array)) #função type é usada para saber q tipo se trata o objeto
print(array)
#retorna um vetor


<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
data = [[1,2,3],[4,5,6]]
array = np.array(data)
#dizer quantas linhas e colunas
print(array.ndim)
print(array.shape)
print("(Obs: 2 linhas e 3 colunas)")

2
(2, 3)
(Obs: 2 linhas e 3 colunas)


In [11]:
#mesma coisa que o anterior
import numpy as np

arr = [[1,2,3],[4,5,6]]
dimension = np.ndim(arr) #array com parametro
print(dimension)


2


In [13]:
#abastecedo os array
import numpy as np
print(np.zeros(10))
print(np.ones(10))
print(np.arange(20))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#arange (inicio, fim e quantidade de saltos)
#arange é o range junto com o objeto
import numpy as np
print(np.arange(0,10,1))
print(np.arange(0,10,2))
print(np.arange(0,10,3))


In [ ]:
#geração de numeros aleatorios
#e cada um do numero ele coloca em um vetor
import numpy as np
print(np.random.rand(1))
print(np.random.rand(2))
print(np.random.rand(3))

In [ ]:
#mesma coisa, mas com linhas e colunas
import numpy as np
print(np.random.rand(1))
print(np.random.rand(2))

In [21]:
#randint = gera numeros inteiros
#gera uma array de 6 elementos com numero inteiros ate o valor 100
import numpy as np
x = np.random.randint(100, size =(6))
print(x)

[71 30 64 80 29  1]


In [ ]:
#computador é incapaz de gerar numeros aleatorios, ele pega valores na memoria ou no registrador....

In [22]:
#usado para pegar a maior moda, media...
#vai pegar o maior e o menor numero do array
import numpy as np
vetor = np.random.randint(100, size = (3))
print(vetor)
print(vetor.max())
print(vetor.min())


[64 21 26]
64
21


In [23]:
#gerar um vetor aleatorio usa a função dtype para saber de que tipo é o dado
import numpy as np
vetor = np.random.rand(3)
print(vetor.dtype)


float64


In [24]:
import numpy as np
vetor = np.arange(3)
print(vetor.dtype)

int64


In [25]:
#ajuda em limpeza de tabela
#tipo de dado homogeneo
#substituir uma parte do vetor
import numpy as np
vetor = np.arange(1,20,1)
print(vetor)
vetor[1:6] = 20
print(vetor)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1 20 20 20 20 20  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [26]:
#pegar uma parte do vetor e coloca em outro vetor
import numpy as np
vetor = np.arange(1,20,1)
print(vetor)
vetor1 = vetor[1:6]
print(vetor1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[2 3 4 5 6]


In [27]:
#calculo matematico
import numpy as np
vetor = np.arange(4)
print(np.exp(vetor)) #calcula a exponenciação
print(np.sqrt(vetor)) #calcula o quadrado


[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]


In [35]:
#ler um array que esta no arq txt
#"nan" é dado não reconhecido
#pegar dados do powerBI
import numpy as np
from numpy import genfromtxt
data = genfromtxt('array.txt', delimiter = ",")
print(data)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [38]:
#indica o tipo de dados q vai pra dentro do vetor e um delimitador
import numpy as np
data = np.loadtxt("array.txt", dtype=int, delimiter = ",")
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
